### ISSUE TITLE
API controller is not catching exceptions from user manager

### ISSUE THREAD

**Issue by cdamken** [nextcloud/registration#110]
Since ownCloud 10.0.4 for security reasons, the username must be at least 3 characters long:
https://github.com/owncloud/core/pull/29198

When users try to register and uses only 2 caracters, he does not get any error, but in log files are shown:
```
{"reqId":"VN8OEVXbi3G6mGkBKJvN","level":3,"time":"2017-12-18T17:05:43+01:00","remoteAddr":"91.45.209.38","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/registration/verify/YHVRMZ","message":"Undefined index: errormsgs at /var/www/owncloud/apps/registration/templates/form.php#9"}
{"reqId":"VN8OEVXbi3G6mGkBKJvN","level":3,"time":"2017-12-18T17:05:44+01:00","remoteAddr":"91.45.209.38","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/registration/verify/YHVRMZ","message":"Undefined index: entered_data at /var/www/owncloud/apps/registration/templates/form.php#27"}
{"reqId":"7SWFcWMr2bgDCPUOf7AG","level":3,"time":"2017-12-18T17:05:54+01:00","remoteAddr":"91.45.209.38","user":"--","app":"index","method":"POST","url":"/index.php/apps/registration/verify/YHVRMZ","message":"Exception: {"Exception":"Exception","Message":"The username must be at least 3 characters long","Code":0,"Trace":"
#0 /var/www/owncloud/apps/registration/service/registrationservice.php(273): OC\User\Manager->createUser('ab', 'password')
#1 /var/www/owncloud/apps/registration/controller/registercontroller.php(138): OCA\Registration\Service\RegistrationService->createAccount(Object(OCA\Registration\Db\Registration), 'ab', 'password')
#2 [internal function]: OCA\Registration\Controller\RegisterController->createAccount('YHVRMZ')
#3 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#4 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Registration\Controller\RegisterController), 'createAccount')
#5 /var/www/owncloud/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Registration\Controller\RegisterController), 'createAccount')
#6 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('OCA\Registratio...', 'createAccount', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#7 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#8 /var/www/owncloud/lib/private/Route/Router.php(342): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#9 /var/www/owncloud/lib/base.php(929): OC\Route\Router->match('/apps/registrat...')
#10 /var/www/owncloud/index.php(56): OC::handleRequest()
#11 {main}","File":"/var/www/owncloud/lib/private/User/Manager.php","Line":310}"}
{"reqId":"7SWFcWMr2bgDCPUOf7AG","level":3,"time":"2017-12-18T17:05:54+01:00","remoteAddr":"91.45.209.38","user":"--","app":"PHP","method":"POST","url":"/index.php/apps/registration/verify/YHVRMZ","message":"Cannot declare class OC_Theme, because the name is already in use at /var/www/owncloud/apps/theme-enterprise/defaults.php#16"}
```

A security problem with the ap is that the username and password is shown in plain text, the admin can see the password too!

**Comment by cdamken** [comment]
@pellaeon Can you provide feedback?

**Comment by nickvergessen** [comment]
The api controller seems to not catch those exceptions and therefor does not return something useful in such cases.

**Comment by cdamken** [comment]
Ok, thank you.

**Comment by cdamken** [comment]
Now, that you own the repository, will be still done the request that I made for oC or not anymore?

**Comment by nickvergessen** [comment]
Well we will fix the issue, but not sure the app will work with oC anymore in the future

**Comment by cdamken** [comment]
I understand. thank you anyway

**Comment by nickvergessen** [comment]
Exceptions are catched properly now
